# .github/workflows/example.yml

name: Merge upstream branches

on:
  schedule:
    - cron: '* * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git Config
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: Merge upstream
        run: |
          git pull --unshallow
          git remote add upstream https://github.com/arkadiyt/bounty-targets-data.git
          git fetch upstream

          branches_to_merge=("feature/x" "master")

          for branch in "${branches_to_merge[@]}"; do
            git checkout -b $branch origin/$branch
            git merge --no-edit upstream/$branch
            git push origin $branch
          done
