name: Sync Fork

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TG908/fork-sync@v1.6.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: arkadiyt
          head: main
          base: main

      - name: 切换到正确的目录
        run: cd bounty-targets-data

      - name: 获取提交信息并推送更改到Fork
        if: success()
        run: |
          COMMIT_MESSAGES=$(git log --pretty=format:"%h - %s" --reverse HEAD..HEAD@{1})
          echo "::set-output name=commit_messages::$COMMIT_MESSAGES"
          git push origin main

      - name: 向 Discord 发送通知
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content":"Fork 同步完成！\n\n更新内容:\n'"${{ steps.get_commit_messages.outputs.commit_messages }}"'"}' \
            $DISCORD_WEBHOOK_URL
