name: Sync Fork

on:
  push:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: TG908/fork-sync@v1.6.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner:  arkadiyt
          head: main
          base: main

      - name: Send Discord Notification
        if: success()
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_URL=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/arkadiyt/repo/compare/main...HEAD | jq -r .html_url)
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content":"Fork sync completed!\n\nChanges:\n\n'"$COMMIT_URL"'"}' \
            $DISCORD_WEBHOOK_URL
