# .github/workflows/sync.yml

name: 同步上游分支

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 仓库
        uses: actions/checkout@v2

      - name: 配置 Git 用户信息
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'

      - name: 添加上游远程
        run: git remote add upstream https://github.com/arkadiyt/bounty-targets-data.git

      - name: 获取上游更改
        run: git fetch upstream

      - name: 合并上游分支到 feature/x
        run: |
          git checkout arkadiyt/bounty-targets-data
          git merge --no-edit upstream/arkadiyt/bounty-targets-data
          git push origin arkadiyt/bounty-targets-data

      - name: 合并上游分支到 main
        run: |
          git checkout master
          git merge --no-edit upstream/main
          git push origin main
